title: K++
author: kristavan
email: vanderhorst.20@wright.edu # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  My cozy nook of the internet.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kristavan.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  kristavan # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: Krista Vanderhorst
  links:
    - https://github.com/kristavan

disqus:
  shortname: kristavan # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
